**pandas**

pandas两个主要数据结构：Series和DataFrame

In [1]:
import pandas as pd

In [109]:
from pandas import Series,DataFrame

Series是一种类似于一维数组的对象，它由一组数据（各种NumPy数据类型）以及一组与之相关的数据标签（即索引）组成。

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

通过Series的values和index属性获取其数组表示形式和索引对象。

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3],index = ["d","b","a","c"])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

通过索引取值

In [9]:
obj2["a"]

-5

In [10]:
obj2["d"]

4

In [11]:
obj2[["c","a","b"]]

c    3
a   -5
b    7
dtype: int64

In [12]:
obj2[obj2>2]

d    4
b    7
c    3
dtype: int64

In [13]:
obj2 * 2

d     8
b    14
a   -10
c     6
dtype: int64

In [15]:
import numpy as np
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

将Series看成一个定长的有序字典

In [16]:
"b" in obj2

True

In [17]:
'e' in obj2

False

通过字典创建Series

In [18]:
sdata = {"Ohio":35000,"Texas":71000,"Oregon":16000,"Utah":5000}

In [19]:
obj3 = pd.Series(sdata) 

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

调整顺序

In [21]:
states = ['Califonia','Ohio','Oregon','Texas']

In [22]:
obj4 = pd.Series(sdata,index=states)

In [23]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

pandas和Series中isnull和notnull都可以检测缺数值

In [24]:
pd.isnull(obj4)

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [25]:
pd.notnull(obj4)

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

In [26]:
obj4.isnull()

Califonia     True
Ohio         False
Oregon       False
Texas        False
dtype: bool

In [27]:
obj4.notnull()

Califonia    False
Ohio          True
Oregon        True
Texas         True
dtype: bool

series可以自动按index来排序

In [28]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [29]:
obj4

Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
dtype: float64

In [30]:
obj3+obj4

Califonia         NaN
Ohio          70000.0
Oregon        32000.0
Texas        142000.0
Utah              NaN
dtype: float64

serice自身和它的index都有一个name属性，这能和其他pandas的函数进行整合：

In [31]:
obj4.name = 'population'

In [32]:
obj4.index.name = 'state'

In [33]:
obj4

state
Califonia        NaN
Ohio         35000.0
Oregon       16000.0
Texas        71000.0
Name: population, dtype: float64

Series的索引可以通过赋值的方式进行修改。

In [34]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [36]:
obj.index = ["Bob","Steve","Jeff","Ryan"]

In [37]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

**DataFrame**

DataFrame是一个表格型的数据结构，它含有一组有序的列，每列可以是不同的值类型（数值、字符串、布尔值等）。

In [41]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}

In [39]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2003, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [43]:
frame = pd.DataFrame(data)

In [44]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [46]:
frame.head(3)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7
2  Ohio  2002  3.6

In [47]:
pd.DataFrame(data,columns=['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [48]:
frame2 = pd.DataFrame(data,columns=['year','state','pop','debt'],
                     index = ['one','two','three','four','five','six'])

In [49]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [50]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [51]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

取列

In [52]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

取列

In [53]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

取行

In [54]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

新增一列 并赋值

In [57]:
frame2['debt'] = 16.5

In [58]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [69]:
frame2['debt']=range(6)

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [65]:
frame2['debt'] = np.arange(6.)

In [67]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

将列表或数组赋值给某个列时，其长度必须跟DataFrame的长度相匹配。如果赋值的是一个Series，就会精确匹配DataFrame的索引，所有的空位都将被填上缺失 值：


In [70]:
val = pd.Series([-1.2,-1.5,-1.7],index = ['two','four','five'])

In [71]:
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [73]:
frame2['debt'] = val

In [74]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

删除列 **del**

In [75]:
frame2['eastern'] = frame2.state == 'Ohio'

In [76]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [77]:
del frame2['eastern']

In [78]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

注：通过索引返回的列是数据本身的视图，不是副本，对返回的Series所做的任何操作都是直接对数据本身进行的，除非先进行copy。

In [97]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [98]:
pop

{'Nevada': {2001: 2.4, 2002: 2.9}, 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

外层字典的键作为列，内层键作为行索引

In [92]:
frame3 = DataFrame(pop)

In [93]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

转置

In [94]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

指定index：

In [101]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}

In [102]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [103]:
 pd.DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

如果设置了DataFrame的index和columns的name属性，则这些信息也会被显示。

In [104]:
frame3.index.name = 'year'
frame3.columns.name = 'state'

In [105]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

values以二维的形式返回数据

In [106]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

**索引对象**

In [111]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [112]:
index =obj.index

In [113]:
index

Index(['a', 'b', 'c'], dtype='object')

In [115]:
index[1:]

Index(['b', 'c'], dtype='object')

In [116]:
index[1] = 'd'      # index对象不可变

TypeError: Index does not support mutable operations

不可变可以使Index对象在多个数据结构之间安全共享。

In [118]:
labels = pd.Index(np.arange(3))

In [119]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [120]:
obj2 = pd.Series([1.5,-2.5,0],index = labels)

In [121]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [122]:
obj2.index is labels

True

In [123]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [125]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [126]:
'Ohio' in frame3.columns

True

In [127]:
2003 in frame3.index

False

**重新索引**

In [128]:
obj = pd.Series([4.5,7.2,-5.3,3.6],index =['d','b','a','c'])

In [129]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

reindex将会根据新索引进行重排。如果某个索引值当前不存在，就引入缺失值。

In [130]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])

In [131]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

在处理时间序列这样的数据时，在重新索引的时候需要做一些插值处理。method选项能做到这一点，比如设定method为ffill，可实现值向前填充。

In [132]:
obj3 = pd.Series(['bule', 'purple', 'yellow'], index=[0, 2, 4])

In [133]:
obj3

0      bule
2    purple
4    yellow
dtype: object

In [138]:
obj3.reindex(range(6),method = 'ffill')

0      bule
1      bule
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [151]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index = ['a','c','d'],
                    columns =[ 'Ohio','Texas','California'])

In [152]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [153]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [154]:
states = ['Texas', 'Utah', 'California']

In [155]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

**丢弃指定轴上的项**

In [157]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [158]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [159]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

对于DataFrame，可以删除任意轴上的索引值。

In [160]:
data = pd.DataFrame(np.arange(16).reshape(4, 4),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [161]:
data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [162]:
data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [163]:
data.drop(['two', 'four'], axis='columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

drop，会修改Series或DataFrame的大小或形状，可以就地修改对象，不会返回新的对象。

In [164]:
obj.drop('c', inplace=True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

注：小心使用inplace，它会销毁所有被删除的数据。

**索引、选取和过滤**

In [166]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [167]:
obj['b']

1.0

In [168]:
obj[1]

1.0

In [171]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

选中行

In [172]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [174]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [175]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

利用标签的切片运算与普通的Python切片运算不同，其末端是包含的。

In [178]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [179]:
obj['b':'c']=5

In [180]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

用一个值或序列对DataFrame进行索引其实就是获取一个或多个列。

In [181]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [182]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [183]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

这种索引方式有几个特殊的情况。首先通过切片或布尔型数组选取数据。

In [184]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [185]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

另一种用法是通过布尔型DataFrame（比如下面这个由标量比较运算得出的）进行索引。

In [186]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [187]:
data[data<5] = 0

In [188]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

用loc和iloc进行选取
+ loc-轴标签
+ iloc-整数索引

In [189]:
data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [190]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [191]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [192]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [193]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [194]:
data.iloc[:,:3][data.three>5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

**整数索引**

In [195]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [196]:
ser[-1]

KeyError: -1

pandas在整数索引上可能会出错。这里我们有一个index包括0，1，2，但是猜测用户想要什么是很困难的。

如果用非整数来做index，就没有歧义了。

In [197]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])
ser2

a    0.0
b    1.0
c    2.0
dtype: float64

In [200]:
ser2[-1]

2.0

为了进行统一，如果轴索引含有整数，数据选取总会使用标签。为了更准确，请使用loc（标签）或iloc（整数）。

In [201]:
ser[:1]

0    0.0
dtype: float64

In [202]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [203]:
ser.iloc[:1]

0    0.0
dtype: float64

**算术运算和数据对齐**

In [204]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [205]:
s2 = pd.Series([2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [206]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [207]:
s2

a    2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [208]:
s1 + s2

a    9.4
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

自动的数据对齐操作在不重叠的索引处引入了NA值。缺失值会在算术运算过程中传播。

In [209]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                   index=['Ohio', 'Texas', 'Colorado'])

In [210]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [211]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [212]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [213]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

如果DataFrame对象相加，没有共用的列或行标签，结果都会是空。

In [214]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [215]:
df1

A
0  1
1  2

In [216]:
df2 

B
0  3
1  4

In [217]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

**在算术方法中填充值**

对于上面那些缺失值，想要填上。

In [220]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), 
                   columns=list('abcd'))

df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), 
                   columns=list('abcde'))
df2.loc[1,'b'] = np.nan

In [219]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [221]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [222]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [223]:
df1.add(df2,fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [225]:
1 / df1

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [226]:
df1.rdiv(1)

a         b         c         d
0       inf  1.000000  0.500000  0.333333
1  0.250000  0.200000  0.166667  0.142857
2  0.125000  0.111111  0.100000  0.090909

In [227]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

**DataFrame和Series之间的运算**

In [228]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [229]:
arr[0]

array([0., 1., 2., 3.])

In [230]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [231]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                    index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]

In [232]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [233]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [234]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [235]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [236]:
series3 = frame['d']
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [237]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [238]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

**函数应用和映射**

In [240]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), 
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.260502  1.373947  0.245199
Ohio   -1.688893 -0.343832 -0.654810
Texas  -1.306479  0.799837  1.690734
Oregon  0.235585 -0.562273 -1.042365

In [241]:
np.abs(frame)

b         d         e
Utah    1.260502  1.373947  0.245199
Ohio    1.688893  0.343832  0.654810
Texas   1.306479  0.799837  1.690734
Oregon  0.235585  0.562273  1.042365

将函数应用到由各列或行所形成的一维数组上。 

In [242]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    2.949396
d    1.936220
e    2.733099
dtype: float64

这里的函数f，计算了一个Series的最大值和最小值的差，在frame的每列都执行了 一次。结果是一个Series，使用frame的列作为索引。

In [243]:
frame.apply(f, axis='columns')

Utah      1.128747
Ohio      1.345062
Texas     2.997212
Oregon    1.277950
dtype: float64

In [244]:
def f(x): 
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [245]:
frame

b         d         e
Utah    1.260502  1.373947  0.245199
Ohio   -1.688893 -0.343832 -0.654810
Texas  -1.306479  0.799837  1.690734
Oregon  0.235585 -0.562273 -1.042365

In [246]:
frame.apply(f)

b         d         e
min -1.688893 -0.562273 -1.042365
max  1.260502  1.373947  1.690734

In [247]:
format = lambda x: '%.2f' % x

In [248]:
frame.applymap(format)

b      d      e
Utah     1.26   1.37   0.25
Ohio    -1.69  -0.34  -0.65
Texas   -1.31   0.80   1.69
Oregon   0.24  -0.56  -1.04

In [249]:
frame['e'].map(format)

Utah       0.25
Ohio      -0.65
Texas      1.69
Oregon    -1.04
Name: e, dtype: object

**排序和排名**

In [250]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [251]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [252]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [253]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [254]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [255]:
obj = pd.Series([4, 7, -3, 2])
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [256]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [257]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [258]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [259]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [260]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [261]:
obj.sort_values()

1   -5
5    0
4    2
3    4
6    4
0    7
2    7
dtype: int64

In [262]:
obj

0    7
1   -5
2    7
3    4
4    2
5    0
6    4
dtype: int64

In [263]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [264]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [265]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2],
                      'a': [0, 1, 0, 1],
                      'c': [-2, 5, 8, -2.5]})
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [266]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

**带有重复标签的轴索引**

In [267]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [268]:
obj.index.is_unique

False

In [269]:
obj['a']


a    0
a    1
dtype: int64

In [270]:
obj['c']

4

In [271]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])
df

0         1         2
a  1.142496 -0.418289 -1.011027
a  0.390242  1.095796 -1.312423
b -0.423090  0.294343 -0.589111
b  1.418610 -0.043914 -1.487572

In [272]:
df.loc['b']

0         1         2
b -0.42309  0.294343 -0.589111
b  1.41861 -0.043914 -1.487572

**汇总和计算描述统计**

In [273]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [274]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [275]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

计算的时候，NA（即缺失值）会被除外，除非整个切片全是NA。我们可以用skipna来跳过计算NA。

In [276]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [277]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [278]:
df.idxmax()

one    b
two    d
dtype: object

In [279]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [280]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [281]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [ ]:
obj.describe()